sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - npm install -g geckodriver
install:
  - pip install -U pip setuptools six urllib3
  - yes "" | sudo -HE ./install.sh
  - pip install -r requirements-dev.txt
  - multiscanner init
script:
  - flake8 --exit-zero .
  - pytest
