sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  apt:
    # Keep these in sync with the dependencies from the install.sh script
    packages:
      - build-essential
      - curl
      - dh-autoreconf
      - gcc
      - libffi-dev
      - libfuzzy-dev
      - python-dev
      - git
      - libssl-dev
      - unzip
      - libmagic-dev
before_install:
  - npm install -g geckodriver
install:
  - pip install -U pip setuptools
script:
  - tox
  - pre-commit run --all-files
