version: '3'
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
     - "script.painless.regex.enabled=true"
     - "xpack.security.enabled=false"
  web:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile_web
    ports:
     - "8000:8000"
  api:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile_api
    ports:
     - "8080:8080"
    depends_on:
     - elastic
